[package]
name = "pinocchio-token-2022"
description = "Pinocchio helpers to invoke Token-2022 program instructions"
version = "0.4.0"
edition = { workspace = true }
license = { workspace = true }
readme = "./README.md"
repository = { workspace = true }

[lib]
crate-type = ["rlib"]

[features]
alloc = ["pinocchio-token/alloc"]

[dependencies]
pinocchio-token = { workspace = true }
solana-account-view = { workspace = true }
solana-address = { workspace = true, features = ["decode", "nullable"] }
solana-instruction-view = { workspace = true, features = ["cpi"] }
solana-nullable = { workspace = true }
solana-program-error = { workspace = true }
solana-zero-copy = { workspace = true }

[dev-dependencies]
solana-address = { workspace = true, features = ["curve25519"] }
